### ISSUE TITLE
do a migration for Milestone v0.2

### ISSUE THREAD

**Issue by douglaskline** [douglaskline/trucktrackrepo#263]
this migration should occur after
* modifications to the truck entity (Issue #232 )
* modifications to the location entity (Issue #202)
* seeding of the truck entity (Issue #261)
* seeding of the location entity (Issue #262 )

**Comment by douglaskline** [comment]
- [ ] while recording every command in a markdown file in the docs folder...
- [ ] while making commits after every change...
- [ ] merge pull requests for the location and class modifications
- [ ] make any additional last minute changes to class models
- [ ] merge all changes into main
- [ ] follow examples in the docs folder
- [ ] create the migration
- [ ] create the sql script
- [ ] run the sql script on the sql azure database
- [ ] scaffold all model controllers, views - make sure they are in the correct folders
- [ ] make sure everything runs - be able to add/remove/edit/list every entity
- [ ] do the final commit, and issue pull request
- [ ] quickly merge the pull request
